### ISSUE TITLE
How can I use this? Do I need to compile the code?

### ISSUE THREAD

**Issue by UnReallAvocado** [JReverse/DiscordDMNuker#10]
Hi, I having problem with running this. How could I run the file?

**Comment by JReverse** [comment]
https://github.com/JReverse/DiscordDMNuker/releases/tag/1.5

**Comment by UnReallAvocado** [comment]
> https://github.com/JReverse/DiscordDMNuker/releases/tag/1.5

Is the token generator still working? If yes, how could I use it?

**Comment by JReverse** [comment]
This is not a token gen but a dm clearer.
